### ISSUE TITLE
Better design on frontpage

### ISSUE THREAD

**Issue by Anachron** [dbashford/mimosa.io#4]
I don't really like the current mix of colors and images and gradients on the frontpage. It's a mix of yellow, brown & orange. Also the page itself is not logical, sections don't repeat their pattern and are not split perfectly.

Here is my idea:

%%%%%%%%%%
Navigation
%%%%%%%%%%

(More soft background, make the text eye-catching)
{Logo as text, make it shine when hovered, link to Github}
{Shorttext] (Get started)
{VeryLongTextThatDescribesWhatMimosaDoes}
(Remove "Mimosa on Github" button)

%%%%%%%%%%
Download [Github] | Share [Twitter] | Discuss [Google] | Release Notes | Presentation
(Big buttons)
%%%%%%%%%%

Features 
(Remove images, replace it with font-awesome, change background gradient)
.....

%%%%%%%%%%
But that's not all
%%%%%%%%%%

Compilers
.....

%%%%%%%%%%

Module Management
.....

%%%%%%%%%%

Ready to mix it up?
{Throw in some examples for starter skeletons}
Or start over with a fresh app [Get Started]

Please note, these are just suggestions. If you want I can put up a small example.

**Comment by dbashford** [comment]
There's a lot I don't understand there, but let me try..
1. I know there's definitely a need to get something onto the front page to discuss how easy it is to get started. (I'm going to close that issue and discuss it here) I would suggest it goes right at the top under the logo and initial sentence on what mimosa is.  Not at the bottom.  The bottom was just a call to action to keep you from having to scroll up.
2. I would like to find a way to better merge the 2nd section with the links and github twitter stuff so that they are side by side with the preso, all taking up less vertical space.  Preso one side, links on the other.  The preso IS the "VeryLongTextThatDescribesWhatMimosaDoes" except in a really digestible format.  I never read really long text on a front-page of a site like mimosa.io.  I need quick blurbs.  I want the preso included on the page, but it doesn't need to take up all that real estate.
3. I'm not sure what is gained by transforming the logo to text other than to be able to shine the word, which isn't the biggest win.  And I'm not sure having it link to github makes sense.  
4. The following things are all important to me: a) some clear link to github, b) link of stargazers and forks, c) number  of followers and tweets d) release notes, e) link to discuss group.  There are plenty of opportunities to "get started" so that link can go.  
5. Also not sure what is gained by switching to font-awesome, other than to just do it.  They are also likely missing a Bower icon. =)

No matter what happens, it needs to be baby steps to the proper layout and content before I'd concern myself with things like backgrounds, gradients and icons.

**Comment by Anachron** [comment]
1.) Okay, I agree with you. First talk about what it is, then about how easy it is to get started. (Maybe with provoking slogan like "Try to find out what you have been missed all the time")  

2.) Again I can see your point. So put the download, release notes and links to the code on the left side, put discussion, slides and twitter on the right side? 

3.) The main deal is: You can use a custom font, make the logo glow and attract the eye to that position. Once the eye is caught, go and let it find the download & help links soon. This way it's not so confusing for the user, since the current frontpage is all with shining objects everywhere. The eye doesn't know where to go to first.

4.) Here aswell, I completely agree with your points.

5.) FA 4.0 is out http://fortawesome.github.io/Font-Awesome/whats-new/. I suggest using the twitter icon http://fortawesome.github.io/Font-Awesome/icon/twitter/. It is vector-based and completely styleable with css. The main deal would be to not need different icon based on browser scale (desktop, tablet, phone) and easy styling options.

So, let's dig into it!

**Comment by dbashford** [comment]
Closing this out.  I'm happy with the design, especially after the tweaks made the last few days.  And I enjoy the color palette.

There are specific things missing, like a build tool throwdown table and a super simple Quick Start, but those can be captured separately.
